#!/usr/bin/env bash
## based off of https://pickard.cc/posts/git-identity-home-manager/

# check if we are in a git repository
if ! git status --porcelain; then
    exit 128
fi
# get each set of usernames from the git config
IDENTITIES=$(git config --global --name-only --get-regexp "user.*..name" | sed -e 's/^user.//' -e 's/.name$//')
# filter them with fzf
ID=$(echo "${IDENTITIES}" | fzf -e -1 +m -q "$1")
if ! git config --global --get-regexp "user.${ID}.name" > /dev/null; then
    echo "Please use a valid git identity
Options:"
    git config --global --name-only --get-regexp "user.*..name" | sed -e 's/^user.//' -e 's/.name$//' -e 's/^/\t/'
    exit 1
fi
# set the ID locally in each repo (eg in the repo's .git/config)
git config user.name "$(git config user.${ID}.name)"
git config user.email "$(git config user.${ID}.email)"

echo "Name: $(git config user.name)"
echo "Email: $(git config user.email)"

# if ! git config --global --get-regexp "user.${ID}.sshKey" > /dev/null; then
#     git config core.sshCommand "ssh -i $(git config user.${ID}.sshKey)"
#     echo "SSH Key: $(git config user.${ID}.sshKey)"
# else
#     echo "SSH Key: default"
# fi
